### ISSUE TITLE
Flagella

### ISSUE THREAD

**Issue by Ruar-p** [jonahshader/alife-tournament#5]
Implement Flagella, the tool the creature will use to propel itself through the environment.

**Comment by jonahshader** [comment]
Do we want this to be a constant thrust proportional to the 'use' amount that comes from the creature's brain output? Or should it have more complex behavior, like building up an impulse that is released to propel it forward?

**Comment by jonahshader** [comment]
For now I will implement the constant thrust version, but we could consider variants
