### ISSUE TITLE
PhysicsObject

### ISSUE THREAD

**Issue by jonahshader** [jonahshader/alife-tournament#9]
PhysicsObject is a class that extends Group. It has a move method that takes in delta time and uses that to integrate acceleration and velocity using euler integration, basically: vel += accel * dt;  pos += vel * dt;

**Comment by jonahshader** [comment]
Note: Since PhysicsObject extends Group, this logic should occur in the act(float dt) method. Just override it and call super.act(dt) after the logic.

**Comment by rfrost114** [comment]
Parent child system from Group
Rendering
